/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ErrorImport } from './routes/error'
import { Route as RootIndexImport } from './routes/root/index'

// Create/Update Routes

const ErrorRoute = ErrorImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const RootIndexRoute = RootIndexImport.update({
  id: '/root/',
  path: '/root/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/root/': {
      id: '/root/'
      path: '/root'
      fullPath: '/root'
      preLoaderRoute: typeof RootIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/error': typeof ErrorRoute
  '/root': typeof RootIndexRoute
}

export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/root': typeof RootIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/error': typeof ErrorRoute
  '/root/': typeof RootIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/error' | '/root'
  fileRoutesByTo: FileRoutesByTo
  to: '/error' | '/root'
  id: '__root__' | '/error' | '/root/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ErrorRoute: typeof ErrorRoute
  RootIndexRoute: typeof RootIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  ErrorRoute: ErrorRoute,
  RootIndexRoute: RootIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/error",
        "/root/"
      ]
    },
    "/error": {
      "filePath": "error.tsx"
    },
    "/root/": {
      "filePath": "root/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
